swagger: '2.0'
info:
  version: '1.0.0'
  title: '[Demo] Orders API (WIP)'
  description: |
    Teamplate API conforming to adidas API Guidelines.
    This API is [documented at Apiary](http://docs.demotemplatewip.apiary.io)
    and [stored on GitHub](https://github.com/adidas-group/demo-orders-api).

schemes:
  - https

produces:
  - application/hal+json        # Representation message format
  - application/vnd.error+json  # Error message format

paths:
  /:
    x-summary: API Root
    get:
      summary: Retrieve API Root
      description: The API Root contains the initial set of link relations.
      responses:
        200:
          description: The root of the API
          schema:
            $ref: '#/definitions/hal-root'

  /orders:
    x-summary: List of Orders
    get:
      summary: Retrieve list of Orders
      responses:
        200:
          description: The list of Orders
          schema:
            $ref: '#/definitions/hal-orders'

    post:
      summary: Create a new Order
      consumes:
        - application/json
      parameters:
        - name: Order
          in: body
          description: Order to be created
          required: true
          schema:
            $ref: '#/definitions/order'
      responses:
        201:
          description: Newly created order
          schema:
            $ref: '#/definitions/hal-order'

  /orders/{orderId}:
    x-summary: Order
    parameters:
      - name: orderId
        in: path
        description: Id of the Order
        required: true
        type: string
        x-example: 1234

    get:
      summary: Retrieve Order
      responses:
        200:
          description: A particular Order
          schema:
            $ref: '#/definitions/hal-order'

        404:
          description: The particular Order wasn't found
          headers:
            Content-Type:
              type: string
              default: application/vnd.error+json
          schema:
            $ref: '#/definitions/order-not-found'

    patch:
      summary: Update Order
      consumes:
        - application/json
      parameters:
        - name: Order
          in: body
          description: Partial order update
          required: true
          schema:
            $ref: '#/definitions/order-patch'
      responses:
        200:
          description: The Order was updated
          schema:
            $ref: '#/definitions/hal-order'

    delete:
      summary: Delete Order
      produces: []
      responses:
        204:
          description: The Order was deleted

definitions:
  # API Root
  hal-root:
    type: object
    allOf:
      - $ref: '#/definitions/hal-resource'
    example:
      _links:
        self:
          href: /
        orders:
          href: /orders

  # Orders
  hal-orders:
    type: object
    allOf:
      - $ref: '#/definitions/hal-resource'
    example:
      _links:
        self:
          href: /orders

      _embedded:
        order:
          $ref: '#/definitions/hal-order/example'

  #
  # Order Resource
  #

  # HAL Wrapper
  hal-order:
    type: object
    allOf:
      - $ref: '#/definitions/hal-resource'
      - $ref: '#/definitions/order'
    example:
      _links:
        self:
          href: /orders/1234
      orderNumber: 1234
      itemCount: 42
      status: pending

  # Partial Order
  order-patch:
    type: object
    allOf:
      - $ref: '#/definitions/order'
    example:
      status: cancelled

  # Order
  order:
    type: object
    properties:
      orderNumber:
        type: number
      itemCount:
        type: number
      status:
        type: string
    required:
      - orderNumber
      - itemCount
    example:
      orderNumber: 42
      itemCount: 3
      status: pending

  # Order Not Found Error
  order-not-found:
    type: object
    allOf:
      - $ref: '#/definitions/vnd.error'
    example:
      _links:
        about:
          href: /orders/1234
      message: "cannot find requested order"
      logref: "REQ0001"

  #
  # -- DO NOT EDIT BEYOND THIS POINT --
  #

  # Media Types Definitions

  #
  # application/vnd.error+json
  #
  vnd.error:
    type: object
    allOf:
      - $ref: '#/definitions/hal-resource'
      - type: object
        properties:
          message:
            type: string
          path:
            type: string
          logref:
            type: [string, number]
        required:
          - message

  #
  # application/hal+json defintion
  #
  hal-link-object:
    type: object
    required:
      - href
    properties:
      href:
        type: string
      templated:
        type: boolean
      type:
        type: string
      deprecation:
        type: string
      name:
        type: string
      profile:
        type: string
      title:
        type: string
      hreflang:
        type: string

  hal-curies-link:
    title: HAL Curies Link
    allOf:
      - type: object
        properties:
          templated:
            enum:
              - true
        required:
          - templated
      - $ref: '#/definitions/hal-link-object'

  hal-resource:
    title: HAL Resource Object
    type: object
    properties:
      _links:
        type: object
        additionalProperties:
          # WARN: Should be "anyOf" but "anyOf" isn't supported in Swagger 2.0
          allOf:
            - $ref: '#/definitions/hal-link-object'
            - type: array
              items:
                - $ref: '#/definitions/hal-link-object'
        properties:
          curies:
            # WARN: Should be "anyOf" but "anyOf" isn't supported in Swagger 2.0
            allOf:
              - $ref: '#/definitions/hal-curies-link'
              - type: array
                items:
                  - $ref: '#/definitions/hal-curies-link'
      _embedded:
        type: object
        additionalProperties: true
        # WARN: Apiary doesn't support circular references
        # additionalProperties:
        #   anyOf:
        #     - $ref: '#/definitions/hal-resource'
        #     - type: array
        #       items:
        #         - $ref: '#/definitions/hal-resource'